puppetmaster: set passenger high performance
avoid error on wercker test harness:

    Error: Could not start Service[httpd]:
    Execution of '/sbin/service httpd start' returned 1: Starting httpd:
    [Tue May 19 01:39:59 2015] [warn] module passenger_module is already loaded, skipping
    Syntax error on line 4 of /etc/httpd/conf.d/passenger_extra.conf:
    PassengerHighPerformance must be On or Off
    [FAILED]
    Error: /Stage[main]/Apache::Service/Service[httpd]/ensure:
    change from stopped to running failed: Could not start Service[httpd]:
    Execution of '/sbin/service httpd start' returned 1: Starting httpd:
    [Tue May 19 01:39:59 2015] [warn] module passenger_module is already loaded, skipping
    Syntax error on line 4 of /etc/httpd/conf.d/passenger_extra.conf:
    PassengerHighPerformance must be On or Off
    [FAILED]