pin an indirect dependency for older ruby
Avoid error:

    ERROR:  Error installing etcd:
            mixlib-log requires Ruby version >= 2.2.

The error is caused because `etcd` requires mixlib-log > 0.